# Generated by Django 2.2.16 on 2023-03-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230323_1820'),
        ('posts', '0003_auto_20230324_1720'),
    ]

    operations = [
    ]
